# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
import  os


class Ui_Form(QtWidgets.QWidget):

    def __init__(self):
        super().__init__()
        self.mapping = {0: " -n", 1: " -w", 2: " -m", 3: " -c", 4: " -h", 5: " -t", 6: " -r"}
        self.l = [False for _ in range(7)]
        self.txt = ""
        self.result = ""
        self.cwd = os.getcwd()
        self.file_name = ""
        self.filetype = ""



    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(550, 652)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.pushButton)
        self.pushButton_4 = QtWidgets.QPushButton(Form)
        self.pushButton_4.setObjectName("pushButton_4")
        self.verticalLayout.addWidget(self.pushButton_4)
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.textEdit = QtWidgets.QTextEdit(Form)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.checkBox = QtWidgets.QCheckBox(Form)
        self.checkBox.setObjectName("checkBox")
        self.verticalLayout.addWidget(self.checkBox)
        self.checkBox_3 = QtWidgets.QCheckBox(Form)
        self.checkBox_3.setObjectName("checkBox_3")
        self.verticalLayout.addWidget(self.checkBox_3)
        self.checkBox_4 = QtWidgets.QCheckBox(Form)
        self.checkBox_4.setObjectName("checkBox_4")
        self.verticalLayout.addWidget(self.checkBox_4)
        self.checkBox_2 = QtWidgets.QCheckBox(Form)
        self.checkBox_2.setObjectName("checkBox_2")
        self.verticalLayout.addWidget(self.checkBox_2)
        self.checkBox_6 = QtWidgets.QCheckBox(Form)
        self.checkBox_6.setObjectName("checkBox_6")
        self.verticalLayout.addWidget(self.checkBox_6)
        self.checkBox_7 = QtWidgets.QCheckBox(Form)
        self.checkBox_7.setObjectName("checkBox_7")
        self.verticalLayout.addWidget(self.checkBox_7)
        self.checkBox_5 = QtWidgets.QCheckBox(Form)
        self.checkBox_5.setObjectName("checkBox_5")
        self.verticalLayout.addWidget(self.checkBox_5)
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout.addWidget(self.pushButton_2)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.textBrowser = QtWidgets.QTextBrowser(Form)
        self.textBrowser.setObjectName("textBrowser")
        self.verticalLayout.addWidget(self.textBrowser)
        self.pushButton_3 = QtWidgets.QPushButton(Form)
        self.pushButton_3.setObjectName("pushButton_3")
        self.verticalLayout.addWidget(self.pushButton_3)
        self.gridLayout.addLayout(self.verticalLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        # 信号连接
        # btn
        self.pushButton.clicked.connect(self.btn_select_file)  # 选择
        self.pushButton_4.clicked.connect(self.btn_input_words)  # 导入
        self.pushButton_2.clicked.connect(self.btn_run_dll)  # 运行
        self.pushButton_3.clicked.connect(self.btn_save_file)  # 导出

        # textEdit
        # 存在效率问题
        self.textEdit.textChanged.connect(self.txt_content_change)
    def btn_select_file(self):
        self.file_name, self.filetype = QtWidgets.QFileDialog.getOpenFileName(self,
                                                                              "选取文件",
                                                                              self.cwd,
                                                                              "Text Files (*.txt)")
        self.label.setText("选择的文件: " + self.file_name)

    def btn_input_words(self):
        if not os.path.isfile(self.file_name):
            QtWidgets.QMessageBox.critical(self, "错误", "文件" + self.file_name + "不存在!")
        else:
            f = open(self.file_name, 'r')
            # 文件占用异常？
            try:
                print("进行读")
                all_the_text = f.read()
                print(all_the_text)
                self.txt = all_the_text
                self.textEdit.setText(all_the_text)
            except:
                QtWidgets.QMessageBox.critical(self, "错误", "文件内容过长!")
            finally:
                f.close()

    def btn_run_dll(self):


        return

    def btn_save_file(self):

        return

    def txt_content_change(self):
        self.txt = self.textEdit.toPlainText()

    def checkbox_choose(self):
        self.l[0] = self.checkBox.isChecked()
        self.l[1] = self.checkBox_2.isChecked()
        self.l[2] = self.checkBox_3.isChecked()
        self.l[3] = self.checkBox_4.isChecked()
        self.l[4] = self.checkBox_5.isChecked()
        self.l[5] = self.checkBox_6.isChecked()
        self.l[6] = self.checkBox_7.isChecked()

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "选择的文件:"))
        self.pushButton.setText(_translate("Form", "选择文件"))
        self.pushButton_4.setText(_translate("Form", "导入(会自动覆盖已写入的单词)"))
        self.label_4.setText(_translate("Form", "或在下方输入单词:"))
        self.label_2.setText(_translate("Form", "启动选项:"))
        self.checkBox.setText(_translate("Form", "-n"))
        self.checkBox_3.setText(_translate("Form", "-w"))
        self.checkBox_4.setText(_translate("Form", "-m"))
        self.checkBox_2.setText(_translate("Form", "-c"))
        self.checkBox_6.setText(_translate("Form", "-h"))
        self.checkBox_7.setText(_translate("Form", "-t"))
        self.checkBox_5.setText(_translate("Form", "-r"))
        self.pushButton_2.setText(_translate("Form", "运行"))
        self.label_3.setText(_translate("Form", "运行结果:"))
        self.pushButton_3.setText(_translate("Form", "导出结果"))


if __name__ == "__main__":
 app = QtWidgets.QApplication(sys.argv)
 widget = QtWidgets.QWidget()
 ui = Ui_Form()
 ui.setupUi(widget)
 widget.show()
 sys.exit(app.exec_())